export const modelLinks = {
    "chatgpt-4o-latest": { url: "https://openai.com/index/hello-gpt-4o/", organization: "OpenAI", displayName: "ChatGPT-4o" },
    "chatgpt-4o-latest-0903": { url: "https://openai.com/index/hello-gpt-4o/", organization: "OpenAI", displayName: "ChatGPT-4o", version: "2024-09-03" },
    "chatgpt-4o-latest-2025-01-29": { url: "https://help.openai.com/en/articles/9624314-model-release-notes", organization: "OpenAI", displayName: "ChatGPT-4o", version: "2025-01-29" },
    "chatgpt-4o-latest-2025-03-27": { url: "https://x.com/OpenAIDevs/status/1905335104211185999?t=pmYR2_xGFyWs1xOGuNxRsw&s=19", organization: "OpenAI", displayName: "ChatGPT-4o", version: "2025-03-27" },
    "claude-3-5-sonnet-20240620": { url: "https://www.anthropic.com/news/claude-3-5-sonnet", organization: "Anthropic", displayName: "Claude 3.5 Sonnet", version: "2024-06-20" },
    "claude-3-5-sonnet-20241022": { url: "https://www.anthropic.com/news/3-5-models-and-computer-use", organization: "Anthropic", displayName: "Claude 3.5 Sonnet", version: "2024-10-22" },
    "claude-3-5-haiku-20241022": { url: "https://www.anthropic.com/claude/haiku", organization: "Anthropic", displayName: "Claude 3.5 Haiku", version: "2024-10-22" },
    "claude-3-haiku-20240307": { url: "https://www.anthropic.com/claude", organization: "Anthropic", displayName: "Claude 3 Haiku", version: "2024-03-07" },
    "claude-3-opus-20240229": { url: "https://www.anthropic.com/claude", organization: "Anthropic", displayName: "Claude 3 Opus", version: "2024-02-29" },
    "claude-3-sonnet-20240229": { url: "https://www.anthropic.com/claude", organization: "Anthropic", displayName: "Claude 3 Sonnet", version: "2024-02-29" },
    "claude-3-7-sonnet-thinking": { url: "https://www.anthropic.com/news/claude-3-7-sonnet", organization: "Anthropic", displayName: "Claude 3.7 Sonnet Thinking", version: "2025-02-19", reasoner: true },
    "claude-3-7-sonnet": { url: "https://www.anthropic.com/news/claude-3-7-sonnet", organization: "Anthropic", displayName: "Claude 3.7 Sonnet", version: "2025-02-19" },
    "claude-3-7-sonnet-20250219-thinking-64k": { url: "https://www.anthropic.com/news/claude-3-7-sonnet", organization: "Anthropic", displayName: "Claude 3.7 Sonnet Thinking", version: "2025-02-19", reasoner: true },
    "claude-3-7-sonnet-20250219-base": { url: "https://www.anthropic.com/news/claude-3-7-sonnet", organization: "Anthropic", displayName: "Claude 3.7 Sonnet", version: "2025-02-19" },
    "command-r": { url: "https://docs.cohere.com/docs/models", organization: "Cohere", displayName: "Command R" },
    "command-r-08-2024": { url: "https://docs.cohere.com/docs/models", organization: "Cohere", displayName: "Command R", version: "2024-08" },
    "command-r-plus": { url: "https://docs.cohere.com/docs/models", organization: "Cohere", displayName: "Command R Plus" },
    "command-r-plus-04-2024": { url: "https://cohere.com/blog/command-r-plus-microsoft-azure", organization: "Cohere", displayName: "Command R Plus", version: "2024-04" },
    "command-r-plus-08-2024": { url: "https://docs.cohere.com/docs/models", organization: "Cohere", displayName: "Command R Plus", version: "2024-08" },
    "deepseek-coder-v2": { url: "https://huggingface.co/deepseek-ai/DeepSeek-V2", organization: "DeepSeek", displayName: "DeepSeek Coder V2" },
    "deepseek-v2.5": { url: "https://huggingface.co/deepseek-ai/DeepSeek-V2.5", organization: "DeepSeek", displayName: "DeepSeek V2.5" },
    "deepseek-v2.5-1210": { url: "https://api-docs.deepseek.com/news/news1210", organization: "DeepSeek", displayName: "DeepSeek V2.5", version: "2024-12-10" },
    "deepseek-v3": { url: "https://api-docs.deepseek.com/news/news1226", organization: "DeepSeek", displayName: "DeepSeek V3" },
    "deepseek-r1": { url: "https://huggingface.co/deepseek-ai/DeepSeek-R1", organization: "DeepSeek", displayName: "DeepSeek R1", reasoner: true },
    "deepseek-r1-distill-qwen-32b": { url: "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B", organization: "DeepSeek", displayName: "DeepSeek R1 Distill Qwen 32B", reasoner: true },
    "deepseek-r1-distill-llama-70b": { url: "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Llama-70B", organization: "DeepSeek", displayName: "DeepSeek R1 Distill Llama 70B", reasoner: true },
    "dracarys-72b-instruct": { url: "https://huggingface.co/abacusai/Dracarys-72B-Instruct", organization: "AbacusAI", displayName: "Dracarys 72B Instruct" },
    "dracarys-llama-3.1-70b-instruct": { url: "https://huggingface.co/abacusai/Dracarys-Llama-3.1-70B-Instruct", organization: "AbacusAI", displayName: "Dracarys Llama 3.1 70B Instruct" },
    "dracarys2-72b-instruct": { url: "https://huggingface.co/abacusai/Dracarys2-72B-Instruct", organization: "AbacusAI", displayName: "Dracarys2 72B Instruct" },
    "dracarys2-llama-3.1-70b-instruct": { url: "https://huggingface.co/abacusai/Dracarys2-Llama-3.1-70B-Instruct", organization: "AbacusAI", displayName: "Dracarys2 Llama 3.1 70B Instruct" },
    "gemini-1.5-flash-001": { url: "https://console.cloud.google.com/vertex-ai/publishers/google/model-garden/gemini-1.5-flash-001", organization: "Google", displayName: "Gemini 1.5 Flash", version: "001" },
    "gemini-1.5-flash-002": { url: "https://developers.googleblog.com/en/updated-production-ready-gemini-models-reduced-15-pro-pricing-increased-rate-limits-and-more/", organization: "Google", displayName: "Gemini 1.5 Flash", version: "002" },
    "gemini-1.5-flash-8b-exp-0827": { url: "https://ai.google.dev/gemini-api/docs/models/experimental-models", organization: "Google", displayName: "Gemini 1.5 Flash 8B Experimental", version: "2024-08-27" },
    "gemini-1.5-flash-8b-exp-0924": { url: "https://ai.google.dev/gemini-api/docs/models/gemini#gemini-1.5-flash-8b", organization: "Google", displayName: "Gemini 1.5 Flash 8B Experimental", version: "2024-09-24" },
    "gemini-1.5-flash-8b-001": { url: "https://ai.google.dev/gemini-api/docs/models/gemini#gemini-1.5-flash-8b", organization: "Google", displayName: "Gemini 1.5 Flash 8B"},
    "gemini-1.5-flash-api-0514": { url: "https://console.cloud.google.com/vertex-ai/publishers/google/model-garden/gemini-1.5-flash-preview-0514", organization: "Google", displayName: "Gemini 1.5 Flash API", version: "2024-05-14" },
    "gemini-1.5-flash-exp-0827": { url: "https://ai.google.dev/gemini-api/docs/models/experimental-models", organization: "Google", displayName: "Gemini 1.5 Flash Experimental", version: "2024-08-27" },
    "gemini-1.5-pro-001": { url: "https://console.cloud.google.com/vertex-ai/publishers/google/model-garden/gemini-1.5-pro-001", organization: "Google", displayName: "Gemini 1.5 Pro", version: "001" },
    "gemini-1.5-pro-002": { url: "https://developers.googleblog.com/en/updated-production-ready-gemini-models-reduced-15-pro-pricing-increased-rate-limits-and-more/", organization: "Google", displayName: "Gemini 1.5 Pro", version: "002" },
    "gemini-1.5-pro-api-0514": { url: "https://console.cloud.google.com/vertex-ai/publishers/google/model-garden/gemini-1.5-flash-preview-0514", organization: "Google", displayName: "Gemini 1.5 Pro API", version: "2024-05-14" },
    "gemini-1.5-pro-exp-0801": { url: "https://ai.google.dev/gemini-api/docs/models/experimental-models", organization: "Google", displayName: "Gemini 1.5 Pro Experimental", version: "2024-08-01" },
    "gemini-1.5-pro-exp-0827": { url: "https://ai.google.dev/gemini-api/docs/models/experimental-models", organization: "Google", displayName: "Gemini 1.5 Pro Experimental", version: "2024-08-27" },
    "gemini-2.0-flash-exp": { url: "https://cloud.google.com/vertex-ai/generative-ai/docs/gemini-v2", organization: "Google", displayName: "Gemini 2.0 Flash Experimental" },
    "gemini-2.0-flash": { url: "https://blog.google/technology/google-deepmind/gemini-model-updates-february-2025/", organization: "Google", displayName: "Gemini 2.0 Flash", version: "001"},
    "gemini-2.0-flash-001": { url: "https://blog.google/technology/google-deepmind/gemini-model-updates-february-2025/", organization: "Google", displayName: "Gemini 2.0 Flash", version: "001" },
    "gemini-2.0-flash-thinking-exp-1219": { url: "https://ai.google.dev/gemini-api/docs/thinking-mode", organization: "Google", displayName: "Gemini 2.0 Flash Thinking Experimental", version: "2024-12-19", reasoner: true },
    "gemini-2.0-flash-thinking-exp-01-21": { url: "https://ai.google.dev/gemini-api/docs/thinking-mode", organization: "Google", displayName: "Gemini 2.0 Flash Thinking Experimental", version: "2025-01-21", reasoner: true },
    "gemini-2.0-flash-lite-preview-02-05": { url: "https://blog.google/technology/google-deepmind/gemini-model-updates-february-2025/", organization: "Google", displayName: "Gemini 2.0 Flash Lite Preview", version: "2025-02-05" },
    "gemini-2.0-pro-exp-02-05": { url: "https://blog.google/technology/google-deepmind/gemini-model-updates-february-2025/", organization: "Google", displayName: "Gemini 2.0 Pro Experimental", version: "2025-02-05" },
    "gemini-exp-1114": { url: "https://ai.google.dev/gemini-api/docs/models/experimental-models", organization: "Google", displayName: "Gemini Experimental 1114", version: "2024-11-14" },
    "gemini-exp-1121": { url: "https://ai.google.dev/gemini-api/docs/models/experimental-models", organization: "Google", displayName: "Gemini Experimental 1121", version: "2024-11-21" },
    "gemini-exp-1206": { url: "https://ai.google.dev/gemini-api/docs/models/experimental-models", organization: "Google", displayName: "Gemini Experimental 1206", version: "2024-12-06" },
    "gemma-2-27b-it": { url: "https://huggingface.co/google/gemma-2-27b", organization: "Google", displayName: "Gemma 2 27B" },
    "gemma-2-9b-it": { url: "https://huggingface.co/google/gemma-2-9b", organization: "Google", displayName: "Gemma 2 9B" },
    "gpt-3.5-turbo-0125": { url: "https://openai.com/index/new-embedding-models-and-api-updates/", organization: "OpenAI", displayName: "GPT-3.5 Turbo", version: "2024-01-25" },
    "gpt-4-0125-preview": { url: "https://openai.com/index/new-models-and-developer-products-announced-at-devday/", organization: "OpenAI", displayName: "GPT-4 Preview", version: "2024-01-25" },
    "gpt-4-0613": { url: "https://openai.com/index/new-models-and-developer-products-announced-at-devday/", organization: "OpenAI", displayName: "GPT-4", version: "2023-06-13" },
    "gpt-4-turbo-2024-04-09": { url: "https://openai.com/index/new-models-and-developer-products-announced-at-devday/", organization: "OpenAI", displayName: "GPT-4 Turbo", version: "2024-04-09" },
    "gpt-4o-2024-05-13": { url: "https://openai.com/index/hello-gpt-4o/", organization: "OpenAI", displayName: "GPT-4o", version: "2024-05-13" },
    "gpt-4o-2024-08-06": { url: "https://openai.com/index/hello-gpt-4o/", organization: "OpenAI", displayName: "GPT-4o", version: "2024-08-06" },
    "gpt-4o-2024-11-20": { url: "https://openai.com/index/hello-gpt-4o/", organization: "OpenAI", displayName: "GPT-4o", version: "2024-11-20" },
    "gpt-4o-mini-2024-07-18": { url: "https://openai.com/index/hello-gpt-4o/", organization: "OpenAI", displayName: "GPT-4o Mini", version: "2024-07-18" },
    "grok-2": { url: "https://x.ai/blog/grok-2", organization: "xAI", displayName: "Grok 2" },
    "grok-2-mini": { url: "https://x.ai/blog/grok-2", organization: "xAI", displayName: "Grok 2 Mini"},
    "grok-2-1212": { url: "https://x.ai/blog/grok-1212", organization: "xAI", displayName: "Grok 2", version: "2024-12-12" },
    "llama-3.1-nemotron-70b-instruct": { url: "https://build.nvidia.com/nvidia/llama-3_1-nemotron-70b-instruct", organization: "NVIDIA", displayName: "Llama 3.1 Nemotron 70B Instruct" },
    "meta-llama-3.1-405b-instruct-turbo": { url: "https://www.together.ai/blog/meta-llama-3-1", organization: "Meta", displayName: "Llama 3.1 405B Instruct Turbo" },
    "meta-llama-3.1-70b-instruct-turbo": { url: "https://www.together.ai/blog/meta-llama-3-1", organization: "Meta", displayName: "Llama 3.1 70B Instruct Turbo",  },
    "meta-llama-3.1-8b-instruct-turbo": { url: "https://www.together.ai/blog/meta-llama-3-1", organization: "Meta", displayName: "Llama 3.1 8B Instruct Turbo",  },
    "llama-3.3-70b-instruct-turbo": { url: "https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct", organization: "Meta", displayName: "Llama 3.3 70B Instruct Turbo",  },
    "mistral-large-2407": { url: "https://huggingface.co/mistralai/Mistral-Large-Instruct-2407", organization: "Mistral AI", displayName: "Mistral Large", version: "2024-07" },
    "mistral-large-2411": { url: "https://huggingface.co/mistralai/Mistral-Large-Instruct-2411", organization: "Mistral AI", displayName: "Mistral Large", version: "2024-11" },
    "mistral-small-2402": { url: "https://docs.mistral.ai/getting-started/models/", organization: "Mistral AI", displayName: "Mistral Small", version: "2024-02" },
    "mistral-small-2409": { url: "https://huggingface.co/mistralai/Mistral-Small-Instruct-2409", organization: "Mistral AI", displayName: "Mistral Small", version: "2024-09" },
    "mistral-small-2501": { url: "https://mistral.ai/en/news/mistral-small-3", organization: "Mistral AI", displayName: "Mistral Small", version: "2025-01" },
    "mixtral-8x22b-instruct-v0.1": { url: "https://huggingface.co/mistralai/Mixtral-8x22B-Instruct-v0.1", organization: "Mistral AI", displayName: "Mixtral 8x22B Instruct",  },
    "o1-mini-2024-09-12": { url: "https://platform.openai.com/docs/guides/reasoning", organization: "OpenAI", displayName: "o1-Mini", version: "2024-09-12", reasoner: true},
    "o1-preview-2024-09-12": { url: "https://platform.openai.com/docs/guides/reasoning", organization: "OpenAI", displayName: "o1 Preview", version: "2024-09-12", reasoner: true },
    "o1-2024-12-17": { url: "https://openai.com/o1/", organization: "OpenAI", displayName: "o1", version: "2024-12-17", reasoner: true },
    "o1-2024-12-17-high": { url: "https://openai.com/o1/", organization: "OpenAI", displayName: "o1 High", version: "2024-12-17", reasoner: true },
    "o1-2024-12-17-low": { url: "https://openai.com/o1/", organization: "OpenAI", displayName: "o1 Low", version: "2024-12-17", reasoner: true },
    "o3-mini-2025-01-31-high": { url: "https://openai.com/index/openai-o3-mini/", organization: "OpenAI", displayName: "o3-Mini High", version: "2025-01-31", reasoner: true },
    "o3-mini-2025-01-31-low": { url: "https://openai.com/index/openai-o3-mini/", organization: "OpenAI", displayName: "o3-Mini Low", version: "2025-01-31", reasoner: true },
    "o3-mini-2025-01-31-medium": { url: "https://openai.com/index/openai-o3-mini/", organization: "OpenAI", displayName: "o3-Mini Medium", version: "2025-01-31", reasoner: true },
    "o3-mini-2025-01-31": { url: "https://openai.com/index/openai-o3-mini/", organization: "OpenAI", displayName: "o3-Mini", version: "2025-01-31", reasoner: true },
    "open-mistral-nemo": { url: "https://huggingface.co/mistralai/Mistral-Nemo-Instruct-2407", organization: "Mistral AI", displayName: "Open Mistral Nemo", version: "2024-07" },
    "phi-3-medium-128k-instruct": { url: "https://huggingface.co/microsoft/Phi-3-medium-128k-instruct", organization: "Microsoft", displayName: "Phi-3 Medium 128K Instruct" },
    "phi-3-medium-4k-instruct": { url: "https://huggingface.co/microsoft/Phi-3-medium-4k-instruct", organization: "Microsoft", displayName: "Phi-3 Medium 4K Instruct" },
    "phi-3-mini-128k-instruct": { url: "https://huggingface.co/microsoft/Phi-3-mini-128k-instruct", organization: "Microsoft", displayName: "Phi-3 Mini 128K Instruct" },
    "phi-3-mini-4k-instruct": { url: "https://huggingface.co/microsoft/Phi-3-mini-4k-instruct", organization: "Microsoft", displayName: "Phi-3 Mini 4K Instruct" },
    "phi-3-small-128k-instruct": { url: "https://huggingface.co/microsoft/Phi-3-small-128k-instruct", organization: "Microsoft", displayName: "Phi-3 Small 128K Instruct" },
    "phi-3-small-8k-instruct": { url: "https://huggingface.co/microsoft/Phi-3-small-8k-instruct", organization: "Microsoft", displayName: "Phi-3 Small 8K Instruct" },
    "phi-3.5-mini-instruct": { url: "https://huggingface.co/microsoft/Phi-3.5-mini-instruct", organization: "Microsoft", displayName: "Phi-3.5 Mini Instruct",  },
    "phi-3.5-moe-instruct": { url: "https://huggingface.co/microsoft/Phi-3.5-MoE-instruct", organization: "Microsoft", displayName: "Phi-3.5 MoE Instruct",  },
    "phi-4": { url: "https://huggingface.co/microsoft/Phi-4", organization: "Microsoft", displayName: "Phi-4"},
    "qwen2.5-72b-instruct-turbo": { url: "https://huggingface.co/Qwen/Qwen2.5-72B-Instruct", organization: "Alibaba", displayName: "Qwen2.5 72B Instruct Turbo",  },
    "qwen2.5-7b-instruct-turbo": { url: "https://huggingface.co/Qwen/Qwen2.5-7B-Instruct", organization: "Alibaba", displayName: "Qwen2.5 7B Instruct Turbo",  },
    "qwen2.5-coder-32b-instruct": { url: "https://huggingface.co/Qwen/Qwen2.5-Coder-32B-Instruct", organization: "Alibaba", displayName: "Qwen2.5 Coder 32B Instruct",  },
    "qwen2.5-max": { url: "https://qwenlm.github.io/blog/qwen2.5-max/", organization: "Alibaba", displayName: "Qwen2.5 Max",  },
    "step-2-16k-202411": { url: "https://www.stepfun.com/#step2", organization: "StepFun", displayName: "Step 2 16K", version: "2024-11" },
    "grok-beta": { url: "https://x.ai/blog/api", organization: "xAI", displayName: "Grok Beta" },
    "amazon.nova-lite-v1:0": { url: "https://aws.amazon.com/ai/generative-ai/nova/", organization: "Amazon", displayName: "Nova Lite",  },
    "amazon.nova-micro-v1:0": { url: "https://aws.amazon.com/ai/generative-ai/nova/", organization: "Amazon", displayName: "Nova Micro",  },
    "amazon.nova-pro-v1:0": { url: "https://aws.amazon.com/ai/generative-ai/nova/", organization: "Amazon", displayName: "Nova Pro",  },
    "qwq-32b-preview": { url: "https://huggingface.co/Qwen/QWQ-32B-Preview", organization: "Alibaba", displayName: "QwQ 32B Preview", reasoner: true },
    "olmo-2-1124-13b-instruct": {url: "https://huggingface.co/allenai/OLMo-2-1124-13B-Instruct", organization: "AllenAI", displayName: "OLMo 2 13B Instruct", version: "2024-11-24"},
    "learnlm-1.5-pro-experimental": {url: "https://ai.google.dev/gemini-api/docs/learnlm", organization: "Google", displayName: "LearnLM 1.5 Pro Experimental", },
    "grok-3-thinking": {url: "https://x.ai/blog/grok-3", organization: "xAI", displayName: "Grok 3 Thinking", reasoner: true},
    "grok-3-beta": {url: "https://x.ai/blog/grok-3", organization: "xAI", displayName: "Grok 3 Beta", version: "2025-04-10"},
    "grok-3-mini-beta-high": {url: "https://x.ai/blog/grok-3", organization: "xAI", displayName: "Grok 3 Mini Beta (High)", reasoner: true, version: "2025-04-10"},
    "gpt-4.5-preview": {url: "https://openai.com/index/introducing-gpt-4-5/", organization: "OpenAI", displayName: "GPT-4.5 Preview", version: "2025-02-27"},
    "gpt-4.5-preview-2025-02-27": {url: "https://openai.com/index/introducing-gpt-4-5/", organization: "OpenAI", displayName: "GPT-4.5 Preview", version: "2025-02-27"},
    "gemini-2.0-flash-lite": {url: "https://developers.googleblog.com/en/start-building-with-the-gemini-2-0-flash-family/", organization: "Google", displayName: "Gemini 2.0 Flash Lite", version: "001"},
    "gemini-2.0-flash-lite-001": {url: "https://developers.googleblog.com/en/start-building-with-the-gemini-2-0-flash-family/", organization: "Google", displayName: "Gemini 2.0 Flash Lite", version: "001"},
    "qwq-32b": { url: "https://qwenlm.github.io/blog/qwq-32b/", organization: "Alibaba", displayName: "QwQ 32B", reasoner: true},
    "mistral-small-2503": { url: "https://mistral.ai/news/mistral-small-3-1", organization: "Mistral AI", displayName: "Mistral Small", version: "2025-03"},
    "gemma-3-27b-it": { url: "https://blog.google/technology/developers/gemma-3/", organization: "Google", displayName: "Gemma 3 27B" },
    "gemma-3-12b-it": { url: "https://blog.google/technology/developers/gemma-3/", organization: "Google", displayName: "Gemma 3 12B" },
    "gemma-3-4b-it": { url: "https://blog.google/technology/developers/gemma-3/", organization: "Google", displayName: "Gemma 3 4B" },
    "perplexity-sonar": { url: "https://perplexity.ai/", organization: "Perplexity", displayName: "Perplexity Sonar" },
    "perplexity-sonar-pro": { url: "https://perplexity.ai/", organization: "Perplexity", displayName: "Perplexity Sonar Pro" },
    "deepseek-v3-0324": {url: "https://huggingface.co/deepseek-ai/DeepSeek-V3-0324", organization: "DeepSeek", displayName: "DeepSeek V3.1", version: "2025-03-24"},
    "gemini-2.5-pro-exp-03-25": {url: "https://blog.google/technology/google-deepmind/gemini-model-thinking-updates-march-2025/", organization: "Google", displayName: "Gemini 2.5 Pro Preview", version: "2025-03-25", reasoner: true},
    "gemini-2.5-pro-preview-03-25": {url: "https://blog.google/technology/google-deepmind/gemini-model-thinking-updates-march-2025/", organization: "Google", displayName: "Gemini 2.5 Pro Preview", version: "2025-03-25", reasoner: true},
    "gemini-2.5-pro-preview-05-06": {url: "https://developers.googleblog.com/en/gemini-2-5-pro-io-improved-coding-performance/", organization: "Google", displayName: "Gemini 2.5 Pro Preview", version: "2025-05-06", reasoner: true},
    "gemini-2.5-pro-preview-06-05-default": {url: "https://blog.google/products/gemini/gemini-2-5-pro-latest-preview/", organization: "Google", displayName: "Gemini 2.5 Pro", version: "2025-06-05", reasoner: true},
    "gemini-2.5-pro-preview-06-05-highthinking": {url: "https://blog.google/products/gemini/gemini-2-5-pro-latest-preview/", organization: "Google", displayName: "Gemini 2.5 Pro (Max Thinking)", version: "2025-06-05", reasoner: true},
    "hunyuan-turbos-20250313": {url: "https://cloud.tencent.com/document/product/1729/104753", organization: "Tencent", displayName: "Hunyuan Turbos", version: "2025-03-13"},
    "azerogpt": {url: "https://azero.soundai.com/#/dashboard", organization: "SoundAI", displayName: "AzeroGPT" },
    "command-a-03-2025": {url: "https://cohere.com/blog/command-a", organization: "Cohere", displayName: "Command A", version: "2025-03"},
    "llama-4-maverick-17b-128e-instruct": {url: "https://ai.meta.com/blog/llama-4-multimodal-intelligence/", organization: "Meta", displayName:"Llama 4 Maverick 17B 128E Instruct"},
    "llama4-maverick-instruct-basic": {url: "https://ai.meta.com/blog/llama-4-multimodal-intelligence/", organization: "Meta", displayName:"Llama 4 Maverick 17B 128E Instruct"},
    "gpt-4.1-2025-04-14": {url: "https://openai.com/index/gpt-4-1/", organization: "OpenAI", displayName: "GPT-4.1", version: "2025-04-14"},
    "gpt-4.1-mini-2025-04-14": {url: "https://openai.com/index/gpt-4-1/", organization: "OpenAI", displayName: "GPT-4.1 Mini", version: "2025-04-14"},
    "gpt-4.1-nano-2025-04-14": {url: "https://openai.com/index/gpt-4-1/", organization: "OpenAI", displayName: "GPT-4.1 Nano", version: "2025-04-14"},
    "o3-2025-04-16-high": {url: "https://openai.com/index/introducing-o3-and-o4-mini/", organization: "OpenAI", displayName: "o3 High", version: "2025-04-16", reasoner: true},
    "o3-2025-04-16-medium": {url: "https://openai.com/index/introducing-o3-and-o4-mini/", organization: "OpenAI", displayName: "o3 Medium", version: "2025-04-16", reasoner: true},
    "o4-mini-2025-04-16-high": {url: "https://openai.com/index/introducing-o3-and-o4-mini/", organization: "OpenAI", displayName: "o4-Mini High", version: "2025-04-16", reasoner: true},
    "o4-mini-2025-04-16-medium": {url: "https://openai.com/index/introducing-o3-and-o4-mini/", organization: "OpenAI", displayName: "o4-Mini Medium", version: "2025-04-16", reasoner: true},
    "gemini-2.5-flash-preview-04-17": {url: "https://blog.google/products/gemini/gemini-2-5-flash-preview/", organization: "Google", displayName: "Gemini 2.5 Flash Preview", version: "2025-04-17", reasoner: true},
    "qwen3-30b-a3b-thinking": {url: "https://qwenlm.github.io/blog/qwen3/", organization: "Alibaba", displayName: "Qwen 3 30B A3B", reasoner: true},
    "qwen3-32b-thinking": {url: "https://qwenlm.github.io/blog/qwen3/", organization: "Alibaba", displayName: "Qwen 3 32B", reasoner: true},
    "qwen3-14b-thinking": {url: "https://qwenlm.github.io/blog/qwen3/", organization: "Alibaba", displayName: "Qwen 3 14B", reasoner: true},
    "learnlm-2.0-flash-experimental": {url: "https://ai.google.dev/gemini-api/docs/learnlm", organization: "Google", displayName: "LearnLM 2.0 Flash Experimental"},
    "qwen3-235b-a22b-thinking": {url: "https://qwenlm.github.io/blog/qwen3/", organization: "Alibaba", displayName: "Qwen 3 235B A22B", reasoner: true},
    "phi-4-reasoning-plus": {url: "https://huggingface.co/microsoft/Phi-4-reasoning-plus", organization: "Microsoft", displayName: "Phi-4 Reasoning Plus", reasoner: true},
    "mistral-medium-2505": {url: "https://mistral.ai/news/mistral-medium-3", organization: "Mistral AI", displayName: "Mistral Medium 3", version: "2025-05"},
    "gemini-2.5-flash-preview-05-20": {url: "https://blog.google/technology/google-deepmind/google-gemini-updates-io-2025/#flash-improvements", organization: "Google", displayName: "Gemini 2.5 Flash", version: "2025-05-20", reasoner: true},
    "claude-4-sonnet-20250514-thinking-64k": { url: "https://www.anthropic.com/news/claude-4", organization: "Anthropic", displayName: "Claude 4 Sonnet Thinking", version: "2025-05-14", reasoner: true },
    "claude-4-sonnet-20250514-base": { url: "https://www.anthropic.com/news/claude-4", organization: "Anthropic", displayName: "Claude 4 Sonnet", version: "2025-05-14" },
    "claude-4-opus-20250514-thinking-32k": { url: "https://www.anthropic.com/news/claude-4", organization: "Anthropic", displayName: "Claude 4 Opus Thinking", version: "2025-05-14", reasoner: true },
    "claude-4-opus-20250514-base": { url: "https://www.anthropic.com/news/claude-4", organization: "Anthropic", displayName: "Claude 4 Opus", version: "2025-05-14" },
    "deepseek-r1-0528": { url: "https://huggingface.co/deepseek-ai/DeepSeek-R1-0528", organization: "DeepSeek", displayName: "DeepSeek R1", reasoner: true, version: "2025-05-28"},
    "o3-pro-2025-06-10-high": {url: "https://platform.openai.com/docs/models/o3-pro", organization: "OpenAI", displayName: "o3 Pro High", version: "2025-06-10", reasoner: true},
    "gemini-2.5-flash-lite-preview-06-17-highthinking": {url: "https://deepmind.google/models/gemini/flash-lite/", organization: "Google", displayName: "Gemini 2.5 Flash Lite Preview (Thinking)", version: "2025-06-17", reasoner: true},
    "gemma-3n-e2b-it": {url: "https://developers.googleblog.com/en/introducing-gemma-3n-developer-guide/", organization: "Google", displayName: "Gemma 3n E2B IT"},
    "gemma-3n-e4b-it": {url: "https://developers.googleblog.com/en/introducing-gemma-3n-developer-guide/", organization: "Google", displayName: "Gemma 3n E4B IT"},
};